services:
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile

  profile.api:
    image: profile.api
    build:
      context: .
      dockerfile: Services/Profile.API/Profile.API/Dockerfile

  profile.api-1:
    image: profile.api-1
    build:
      context: .
      dockerfile: Services/Profile/Profile.API/Dockerfile

  notification.api:
    image: notification.api
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: Services/LifeStyles/WebApplication1/Dockerfile

  lifestyles.api:
    image: lifestyles.api
    build:
      context: .
      dockerfile: Services/LifeStyles/LifeStyles.API/Dockerfile

  subscription.api:
    image: subscription.api
    build:
      context: .
      dockerfile: Services/Subscription/Subscription.API/Dockerfile

  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile

  chatbox.api:
    image: chatbox.api
    build:
      context: .
      dockerfile: Services/ChatBox/ChatBox.API/Dockerfile
